//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_Choferes.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_language_spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_language_spanish() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplicacion_Choferes.Languages.Resource_language_spanish", typeof(Resource_language_spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activado.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicacion Camionero.
        /// </summary>
        internal static string ApplicationTrucker {
            get {
                return ResourceManager.GetString("ApplicationTrucker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicacion Almacen.
        /// </summary>
        internal static string AppStoreHouseTitle {
            get {
                return ResourceManager.GetString("AppStoreHouseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote asignado a camion.
        /// </summary>
        internal static string AssignedLotToTruck {
            get {
                return ResourceManager.GetString("AssignedLotToTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lotes asignados a camionero.
        /// </summary>
        internal static string AssignedLotToTrucker {
            get {
                return ResourceManager.GetString("AssignedLotToTrucker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camion asignado.
        /// </summary>
        internal static string AssignedTruck {
            get {
                return ResourceManager.GetString("AssignedTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar lote a camionero.
        /// </summary>
        internal static string AssignLotToTrucker {
            get {
                return ResourceManager.GetString("AssignLotToTrucker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Productos.
        /// </summary>
        internal static string AssignProducts {
            get {
                return ResourceManager.GetString("AssignProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de estado.
        /// </summary>
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porfavor Completa Todos Los Campos Y Estados.
        /// </summary>
        internal static string CompleteAllBoxAndStatus {
            get {
                return ResourceManager.GetString("CompleteAllBoxAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esquina.
        /// </summary>
        internal static string Corner {
            get {
                return ResourceManager.GetString("Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de creacion.
        /// </summary>
        internal static string DateOfCreation {
            get {
                return ResourceManager.GetString("DateOfCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de envio.
        /// </summary>
        internal static string DateOfShipment {
            get {
                return ResourceManager.GetString("DateOfShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Destino.
        /// </summary>
        internal static string DestinationID {
            get {
                return ResourceManager.GetString("DestinationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destinos.
        /// </summary>
        internal static string Destinations {
            get {
                return ResourceManager.GetString("Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicacion choferes.
        /// </summary>
        internal static string DriversApplication {
            get {
                return ResourceManager.GetString("DriversApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error De Sintaxis.
        /// </summary>
        internal static string ErrorSyntaxis {
            get {
                return ResourceManager.GetString("ErrorSyntaxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha estimada de entrega.
        /// </summary>
        internal static string EstimatedDate {
            get {
                return ResourceManager.GetString("EstimatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Destino.
        /// </summary>
        internal static string IDDestination {
            get {
                return ResourceManager.GetString("IDDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Camion.
        /// </summary>
        internal static string IDTruck {
            get {
                return ResourceManager.GetString("IDTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Camionero.
        /// </summary>
        internal static string IDTrucker {
            get {
                return ResourceManager.GetString("IDTrucker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID No valido.
        /// </summary>
        internal static string InvalidID {
            get {
                return ResourceManager.GetString("InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote encontrado.
        /// </summary>
        internal static string LotFound {
            get {
                return ResourceManager.GetString("LotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Lote.
        /// </summary>
        internal static string LotID {
            get {
                return ResourceManager.GetString("LotID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Lote a asignar.
        /// </summary>
        internal static string LotIDToAssign {
            get {
                return ResourceManager.GetString("LotIDToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote no encontrado.
        /// </summary>
        internal static string LotNotFound {
            get {
                return ResourceManager.GetString("LotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu principal.
        /// </summary>
        internal static string MainMenuSpanish {
            get {
                return ResourceManager.GetString("MainMenuSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar destinos.
        /// </summary>
        internal static string ManageDestinations {
            get {
                return ResourceManager.GetString("ManageDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar lotes.
        /// </summary>
        internal static string ManageLots {
            get {
                return ResourceManager.GetString("ManageLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar productos.
        /// </summary>
        internal static string ManageProducts {
            get {
                return ResourceManager.GetString("ManageProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar envios.
        /// </summary>
        internal static string ManageShipments {
            get {
                return ResourceManager.GetString("ManageShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recorridos.
        /// </summary>
        internal static string ManageTravels {
            get {
                return ResourceManager.GetString("ManageTravels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribucion de productos y lotes.
        /// </summary>
        internal static string ProductAndLotDistribution {
            get {
                return ResourceManager.GetString("ProductAndLotDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto Encontrado.
        /// </summary>
        internal static string ProductFound {
            get {
                return ResourceManager.GetString("ProductFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Producto.
        /// </summary>
        internal static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Producto a asignar.
        /// </summary>
        internal static string ProductIDToAssign {
            get {
                return ResourceManager.GetString("ProductIDToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto No Encontrado.
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recargar.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recorridos.
        /// </summary>
        internal static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por id destino.
        /// </summary>
        internal static string SearchByDestinationID {
            get {
                return ResourceManager.GetString("SearchByDestinationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por id almacen.
        /// </summary>
        internal static string SearchByStoreHouseID {
            get {
                return ResourceManager.GetString("SearchByStoreHouseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscador.
        /// </summary>
        internal static string Searcher {
            get {
                return ResourceManager.GetString("Searcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string SearchProductByID {
            get {
                return ResourceManager.GetString("SearchProductByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona una fila.
        /// </summary>
        internal static string SelectAnIndex {
            get {
                return ResourceManager.GetString("SelectAnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de envio.
        /// </summary>
        internal static string ShipmentDate {
            get {
                return ResourceManager.GetString("ShipmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacen.
        /// </summary>
        internal static string StoreHouse {
            get {
                return ResourceManager.GetString("StoreHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Almacen.
        /// </summary>
        internal static string StoreHouseID {
            get {
                return ResourceManager.GetString("StoreHouseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accion exitosa.
        /// </summary>
        internal static string Successfull {
            get {
                return ResourceManager.GetString("Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Camionero.
        /// </summary>
        internal static string TruckerID {
            get {
                return ResourceManager.GetString("TruckerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camiones y lotes.
        /// </summary>
        internal static string TrucksAndLots {
            get {
                return ResourceManager.GetString("TrucksAndLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de recorrido.
        /// </summary>
        internal static string TypeTravel {
            get {
                return ResourceManager.GetString("TypeTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario encontrado.
        /// </summary>
        internal static string UserFound {
            get {
                return ResourceManager.GetString("UserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifica la informacion ingresada.
        /// </summary>
        internal static string VerifyData {
            get {
                return ResourceManager.GetString("VerifyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver destinos.
        /// </summary>
        internal static string ViewDestinations {
            get {
                return ResourceManager.GetString("ViewDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
